# Made by @Am1nCmd for universal tweaks injection

name: Build and Release Tweaked IPA

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK version"
        default: "16.4"
        required: true
        type: string
      decrypted_ipa_url:
        description: "Direct URL to IPA files"
        default: ""
        required: true
        type: string
      app_name:
        description: "Change App Name"
        default: ""
        required: false
        type: string
      bundle_id:
        description: "Change BundleID"
        required: false
        type: string
      tweaks_url:
        description: "Direct URL to Tweaks (.deb / .dylib)"
        default: ""
        required: true
        type: string
      tweaks_version:
        description: "Tweaks Version"
        default: "1.0.0"
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Tweaked IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter:tree:0 https://github.com/arichornlover/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.1
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare Tweaked iPA
        id: prepare_tweaked
        run: |
          wget "${{ inputs.decrypted_ipa_url }}" --no-verbose -O main/App.ipa
          cd ${{ github.workspace }}/main
          mv App.ipa App.zip
          unzip -q App.zip
          app_version=$(defaults read "$(pwd)/Payload/App.app/Info" CFBundleVersion)
          echo "==> App v$app_version downloaded!"
          sed -i '' "17s#.*#APP_VERSION = ${app_version}#g" Makefile
          echo "app_version=${app_version}" >> $GITHUB_OUTPUT

        env:
          THEOS: ${{ github.workspace }}/theos
          APP_URL: ${{ inputs.decrypted_ipa_url }}

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ inputs.bundle_id }}#g" Makefile                          # Modify the bundle ID
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ inputs.app_name }}#g" Makefile                        # Modify the app name
          sed -i '' "1s#.*#export TARGET = iphone:clang:${{ inputs.sdk_version }}:14.0#g" Makefile # Modify the SDK version
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/App.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ inputs.bundle_id }}\033[0m"

        env:
          THEOS: ${{ github.workspace }}/theos
          TWEAKS_VERSION: ${{ inputs.tweaks_version }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          APP_NAME: ${{ inputs.app_name }}

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.1
        env:
          TWEAKS_VERSION: ${{ inputs.tweaks_version }}
          APP_VERSION: ${{ steps.prepare_tweaked.outputs.app_version }}
        with:
          name: tweakedApp_${{ env.APP_VERSION }}_${{ env.TWEAKS_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWEAKS_VERSION: ${{ inputs.tweaks_version }}
          APP_VERSION: ${{ steps.prepare_tweaked.outputs.app_version }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: v${{ env.APP_VERSION }}-${{ env.TWEAKS_VERSION }}-(${{ github.run_number }})
          name: v${{ env.APP_VERSION }}-${{ env.TWEAKS_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: ${{ env.DRAFT }}
